workspace:
  base: /drone/src
  path: /${DRONE_REPO}/${DRONE_BRANCH}
clone:
  git:
    image: plugins/git
    commands:
      - ls -lah
      - ping baidu.com -w 10
      - pwd
      - whoami
    privileged: true
    volumes:
      - drone-data:/drone
  git2:
    image: plugins/git
    commands:
      - env
pipeline:
  test-prep:
    image: mongo
    commands:
    #- mongoimport --db test_db --collection widgets --type json --file seed.json --jsonArray
    - ls
  test:
    image: mongo
    commands:
    #- mongo --eval "db.widgets.find({});" test_db
    - pwd

services:
  mongo:
    image: mongo
