workspace:
  base: /drone/src
  path: /${DRONE_REPO}/${DRONE_BRANCH}
clone:
  git:
    image: plugins/git
  git2:
    image: plugins/git
    commands:
      - df
      - echo ${DRONE_PREV_COMMIT_SHA} ${DRONE_COMMIT_SHA}
      - git diff --name-status ${DRONE_PREV_COMMIT_SHA}..${DRONE_COMMIT_SHA} 2>&1
      - ls -lah /drone
pipeline:
  alpine-setup-1:
    image: alpine
    volumes:
      - /data:/drone
    commands:
      - ls -lah /drone
