workspace:
  base: /drone/src
  path: /${DRONE_REPO}/${DRONE_BRANCH}
clone:
  git:
    image: plugins/git
  git2:
    image: plugins/git
    commands:
      - df
      - echo ${DRONE_PREV_COMMIT_SHA} ${DRONE_COMMIT_SHA}
      - git diff --name-status ${DRONE_PREV_COMMIT_SHA}..${DRONE_COMMIT_SHA} 2>&1
      - ls -lah /drone
pipeline:
  aline-setup-1:
    image: alpine
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ls -lah /drone
    
services:
  mongo:
    image: mongo
 
